# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
title: "Le conseil en droit social sur-mesure - HOGO Avocats"
meta-desc: "HOGO est une société d’avocats exclusivement dédiée à l’accompagnement des entreprises & associations en droit du travail et droit de la sécurité sociale."
